# Generated by Django 3.1.7 on 2021-03-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='nom',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='prenom',
            new_name='name',
        ),
    ]
